/* ------------------------------------------------------------------ *
 * UI FIXTURES — realistic sample data in the exact shape of the
 * backend API payloads (see ../api). Replace fetchers, not views.
 * All coordinates are LOCAL PLANE metres from survey origin SEAL-01.
 * ------------------------------------------------------------------ */

import type {
  DayStat,
  FieldVisit,
  Place,
  Scenario,
  Scene,
  ServiceHealth,
  SystemOverview,
  VerifyCase,
} from "./types";

export const PLANE = { originId: "SEAL-01", epoch: "2025-W46 retrace" };

/* ================= base cartography (local metres) ================= */

export const SCENE: Scene = {
  roads: [
    { id: "r-hwy", kind: "arterial", name: "Pune–Nashik Hwy · SH-27", widthM: 14,
      path: [{ x: 120, y: 140 }, { x: 2480, y: 1520 }] },
    { id: "r-tilak", kind: "street", name: "Tilak Rd", widthM: 7,
      path: [{ x: 250, y: 1500 }, { x: 1800, y: 420 }] },
    { id: "r-station", kind: "street", name: "Station Rd", widthM: 7,
      path: [{ x: 480, y: 120 }, { x: 1500, y: 1650 }] },
    { id: "r-gaothan", kind: "street", name: "Gaothan Rd", widthM: 6,
      path: [{ x: 900, y: 250 }, { x: 2400, y: 950 }] },
    { id: "r-ram", kind: "lane", name: "Ram Mandir Ln", widthM: 4,
      path: [{ x: 1050, y: 900 }, { x: 1450, y: 1150 }, { x: 1980, y: 1180 }] },
    { id: "r-morya", kind: "street", name: "Morya Colony Rd", widthM: 6,
      path: [{ x: 1600, y: 300 }, { x: 2100, y: 700 }, { x: 2300, y: 1400 }] },
    { id: "r-market", kind: "lane", name: "Market Ln", widthM: 4,
      path: [{ x: 900, y: 1180 }, { x: 980, y: 860 }, { x: 950, y: 560 }] },
    { id: "r-zp", kind: "lane", name: "ZP School Rd", widthM: 4,
      path: [{ x: 700, y: 700 }, { x: 1200, y: 700 }] },
    { id: "r-temple", kind: "lane", name: "Temple St", widthM: 4,
      path: [{ x: 1000, y: 1350 }, { x: 1500, y: 1200 }, { x: 1900, y: 1250 }] },
    { id: "r-bandhara", kind: "track", name: "Bandhara track", widthM: 3,
      path: [{ x: 1400, y: 150 }, { x: 1600, y: 300 }, { x: 1900, y: 360 }] },
    { id: "f-nala", kind: "stream", name: "Kukdi Nala", widthM: 3,
      path: [{ x: 300, y: 150 }, { x: 700, y: 260 }, { x: 1150, y: 240 }, { x: 1600, y: 330 }, { x: 2020, y: 300 }, { x: 2450, y: 420 }, { x: 2600, y: 380 }] },
    { id: "f-rail", kind: "rail", name: "Daund–Manmad line", widthM: 5,
      path: [{ x: 150, y: 1250 }, { x: 900, y: 1180 }, { x: 1700, y: 1120 }, { x: 2600, y: 1090 }] },
  ],
  landmarks: [
    { id: "lm-bus", kind: "stand", label: "Old Bus Stand", at: { x: 730, y: 560 } },
    { id: "lm-ram", kind: "temple", label: "Ram Mandir", at: { x: 1240, y: 858 } },
    { id: "lm-hanuman", kind: "temple", label: "Hanuman Mandir", at: { x: 1995, y: 1242 } },
    { id: "lm-tank", kind: "tank", label: "Morya Water Tank", at: { x: 2140, y: 760 } },
    { id: "lm-school", kind: "school", label: "ZP Primary School", at: { x: 900, y: 700 } },
    { id: "lm-clinic", kind: "clinic", label: "Ambegaon Clinic", at: { x: 560, y: 860 } },
    { id: "lm-well", kind: "well", label: "Stepwell", at: { x: 1720, y: 420 } },
    { id: "lm-bridge", kind: "bridge", label: "Nala Bridge", at: { x: 1600, y: 330 } },
  ],
};

/* ================= resolver scenarios ================= */

const A: Scenario = {
  id: "scn-a",
  raw: "URMI SEPTIC TANK SERVICRS!! 14/2-B, behind old bus stand?? Ambegaon bk, 412406",
  context: "typo-heavy intake · landmark-relative · strong field memory",
  parsed: [
    { t: "URMI SEPTIC TANK SERVICRS", k: "business" },
    { t: "!!", k: "noise" },
    { t: "14/2-B", k: "house-no" },
    { t: "behind old bus stand", k: "landmark" },
    { t: "Ambegaon bk", k: "locality" },
    { t: "412406", k: "pin" },
  ],
  anchor: { x: 820, y: 620 },
  anchorSigmaM: 480,
  memory: { placeId: "PL-AMB-0142", at: { x: 700, y: 580 }, sigmaM: 4.2, lastVerifiedDays: 12 },
  candidates: [
    {
      id: "C-A1", at: { x: 700, y: 580 }, sigmaM: 4.2,
      canonical: "14/2-B, Station Rd (rear), Ambegaon BK 412406",
      source: "Field Memory", sourceRef: "PL-AMB-0142", score: 0.88,
      parts: { text: 0.91, component: 0.93, source: 0.72, evidence: 0.95, memory: 0.97, freshness: 0.94 },
      distFromAnchorM: 126.5, evidenceSupport: 3,
    },
    {
      id: "C-A2", at: { x: 695, y: 585 }, sigmaM: 9.0,
      canonical: "Survey No 14/2-B, Gaothan, Ambegaon BK",
      source: "Municipal Parcel DB", sourceRef: "PRCL-AMB-14/2-B", score: 0.82,
      parts: { text: 0.88, component: 0.9, source: 0.9, evidence: 0.4, memory: 0, freshness: 0.88 },
      distFromAnchorM: 131.9, evidenceSupport: 1,
    },
    {
      id: "C-A3", at: { x: 760, y: 640 }, sigmaM: 60,
      canonical: "Ambegaon BK gaothan (gazette 2004)",
      source: "Gazette Registry", sourceRef: "GAZ-2004-AMB-BK", score: 0.61,
      parts: { text: 0.74, component: 0.58, source: 0.85, evidence: 0, memory: 0, freshness: 0.62 },
      distFromAnchorM: 63.2, evidenceSupport: 0,
      conflict: "gazette epoch 2004 — pre-resurvey",
    },
    {
      id: "C-A4", at: { x: 830, y: 690 }, sigmaM: 210,
      canonical: "PIN 412406 delivery centroid",
      source: "Postal PIN Directory", sourceRef: "PIN-412406", score: 0.44,
      parts: { text: 0.5, component: 0.32, source: 0.55, evidence: 0, memory: 0, freshness: 0.9 },
      distFromAnchorM: 70.7, evidenceSupport: 0,
    },
  ],
  trails: [
    {
      id: "A-t1", outcome: "confirm", label: "EV-2311 · CONFIRMED",
      meta: "CEP 2.8 m · dwell 84 s · 12 d ago",
      points: [{ x: 742, y: 556 }, { x: 733, y: 563 }, { x: 722, y: 570 }, { x: 712, y: 576 }, { x: 705, y: 579 }, { x: 701, y: 580 }],
    },
    {
      id: "A-t2", outcome: "confirm", label: "EV-1977 · CONFIRMED",
      meta: "CEP 3.4 m · 74 d ago",
      points: [{ x: 700, y: 520 }, { x: 699, y: 540 }, { x: 698, y: 556 }, { x: 698, y: 570 }, { x: 699, y: 579 }],
    },
  ],
  pipeline: [
    { stage: "parse", ms: 12, note: "6 tokens · noise stripped · 'SERVICRS'→'services' (edit 2) · house-no 14/2-B ok" },
    { stage: "anchor", ms: 8, note: "locality 'Ambegaon BK' centroid E 000 820 / N 000 620 · σ 480 m · PIN hint cross-ok" },
    { stage: "retrieve", ms: 31, note: "gazette 1 · parcels 1 · PIN 1 · dedupe against memory → 4 candidates" },
    { stage: "memory", ms: 6, note: "prior PL-AMB-0142 hit · σ 4.2 m · verified 12 d ago · warm" },
    { stage: "evidence-prior", ms: 11, note: "3 visits within 150 m of C-A1 · median offset 1.8 m · integrity all clear" },
    { stage: "score", ms: 9, note: "r1 0.88 · r2 0.82 (Δ 0.06) · r1/r2 co-located 5.1 m" },
    { stage: "policy", ms: 3, note: "margin below 0.15 gate, but spatial cluster tight → HUMAN-COMMIT permitted" },
  ],
  gateNote: "r1 and r2 are 5.1 m apart and agree; score margin alone would force field verification.",
};

const B: Scenario = {
  id: "scn-b",
  raw: "Flt 7, Shanti Niwas, 3rd Flr, opp Ram Mandir, Tilak Rd, Chakan 410501",
  context: "well-formed intake · landmark corroborated · warm prior",
  parsed: [
    { t: "Flt 7", k: "unit" },
    { t: "Shanti Niwas", k: "business" },
    { t: "3rd Flr", k: "unit" },
    { t: "opp Ram Mandir", k: "landmark" },
    { t: "Tilak Rd", k: "street" },
    { t: "Chakan", k: "locality" },
    { t: "410501", k: "pin" },
  ],
  anchor: { x: 1210, y: 845 },
  anchorSigmaM: 260,
  memory: { placeId: "PL-CHK-0087", at: { x: 1173, y: 827 }, sigmaM: 6.1, lastVerifiedDays: 34 },
  candidates: [
    {
      id: "C-B1", at: { x: 1172, y: 826 }, sigmaM: 6.1,
      canonical: "Flt 7, Shanti Niwas, TPS-Chakan 3/114, Tilak Rd",
      source: "Municipal Parcel DB", sourceRef: "PRCL-CHK-3/114", score: 0.91,
      parts: { text: 0.95, component: 0.94, source: 0.9, evidence: 0.92, memory: 0.95, freshness: 0.9 },
      distFromAnchorM: 43.9, evidenceSupport: 2,
    },
    {
      id: "C-B2", at: { x: 1198, y: 846 }, sigmaM: 12,
      canonical: "Tilak Rd 114 (gazette 2011)",
      source: "Gazette Registry", sourceRef: "GAZ-2011-TLK-114", score: 0.68,
      parts: { text: 0.8, component: 0.62, source: 0.85, evidence: 0.1, memory: 0, freshness: 0.55 },
      distFromAnchorM: 12.0, evidenceSupport: 0,
      conflict: "holdover number — superseded by TPS resurvey",
    },
    {
      id: "C-B3", at: { x: 1120, y: 870 }, sigmaM: 240,
      canonical: "PIN 410501 delivery centroid",
      source: "Postal PIN Directory", sourceRef: "PIN-410501", score: 0.41,
      parts: { text: 0.52, component: 0.3, source: 0.55, evidence: 0, memory: 0, freshness: 0.9 },
      distFromAnchorM: 93.4, evidenceSupport: 0,
    },
  ],
  trails: [
    {
      id: "B-t1", outcome: "confirm", label: "EV-2306 · CONFIRMED",
      meta: "CEP 2.4 m · 13 Feb",
      points: [{ x: 1120, y: 905 }, { x: 1138, y: 886 }, { x: 1152, y: 866 }, { x: 1160, y: 850 }, { x: 1167, y: 836 }, { x: 1171, y: 828 }],
    },
    {
      id: "B-t2", outcome: "confirm", label: "EV-2064 · CONFIRMED",
      meta: "CEP 3.0 m · 34 d ago",
      points: [{ x: 1220, y: 760 }, { x: 1204, y: 782 }, { x: 1190, y: 800 }, { x: 1180, y: 814 }, { x: 1174, y: 825 }],
    },
  ],
  pipeline: [
    { stage: "parse", ms: 10, note: "7 tokens · unit 'Flt 7' + floor split · 'opp' → landmark relation ACROSS" },
    { stage: "anchor", ms: 7, note: "street × landmark intersect → E 001 210 / N 000 845 · σ 260 m" },
    { stage: "retrieve", ms: 28, note: "parcels 1 · gazette 1 · PIN 1 → 3 candidates · landmark 68 m from r1" },
    { stage: "memory", ms: 5, note: "prior PL-CHK-0087 hit · σ 6.1 m · verified 34 d ago · warm" },
    { stage: "evidence-prior", ms: 9, note: "2 visits converge on r1 · offsets 2.4 / 3.1 m · integrity clear" },
    { stage: "score", ms: 8, note: "r1 0.91 · r2 0.68 (Δ 0.23) · r3 0.41" },
    { stage: "policy", ms: 2, note: "top1 ≥ 0.85 and margin ≥ 0.15 → AUTO-CONFIRM eligible" },
  ],
  gateNote: "Clean pass. Auto-confirm permitted; operator sign-off still recorded to ledger.",
};

const C: Scenario = {
  id: "scn-c",
  raw: "S No 88/1, gaothan side, near Hanuman Mndr, Pune Nashik Hwy, Rajgurunagar 410505",
  context: "memory says one place · fresh evidence says it moved 99.8 m",
  parsed: [
    { t: "S No 88/1", k: "house-no" },
    { t: "gaothan side", k: "locality" },
    { t: "near Hanuman Mndr", k: "landmark" },
    { t: "Pune Nashik Hwy", k: "street" },
    { t: "Rajgurunagar", k: "locality" },
    { t: "410505", k: "pin" },
  ],
  anchor: { x: 1955, y: 1213 },
  anchorSigmaM: 300,
  memory: { placeId: "PL-RJG-0231", at: { x: 1940, y: 1185 }, sigmaM: 5.0, lastVerifiedDays: 210 },
  candidates: [
    {
      id: "C-C1", at: { x: 2008, y: 1258 }, sigmaM: 5.4,
      canonical: "S.No 88/1 (resurvey Nov-2025), Gaothan, Rajgurunagar",
      source: "Municipal Parcel DB", sourceRef: "PRCL-RJG-88/1R", score: 0.79,
      parts: { text: 0.9, component: 0.88, source: 0.9, evidence: 0.9, memory: 0.1, freshness: 0.86 },
      distFromAnchorM: 69.3, evidenceSupport: 1,
      conflict: "99.8 m from stored memory point",
    },
    {
      id: "C-C2", at: { x: 1940, y: 1185 }, sigmaM: 5.0,
      canonical: "S.No 88/1 (gazette 2004) — stored memory",
      source: "Field Memory", sourceRef: "PL-RJG-0231", score: 0.72,
      parts: { text: 0.86, component: 0.84, source: 0.72, evidence: 0.05, memory: 0.55, freshness: 0.22 },
      distFromAnchorM: 32.2, evidenceSupport: 0,
      conflict: "2 refute visits at this point · occupant absent",
    },
    {
      id: "C-C3", at: { x: 1875, y: 1120 }, sigmaM: 180,
      canonical: "PIN 410505 delivery centroid",
      source: "Postal PIN Directory", sourceRef: "PIN-410505", score: 0.46,
      parts: { text: 0.55, component: 0.36, source: 0.55, evidence: 0, memory: 0, freshness: 0.9 },
      distFromAnchorM: 122.6, evidenceSupport: 0,
    },
  ],
  trails: [
    {
      id: "C-t1", outcome: "refute", label: "EV-2309 · NOT_FOUND",
      meta: "dwell 210 s at stored point · 14 Feb",
      points: [{ x: 1905, y: 1130 }, { x: 1918, y: 1152 }, { x: 1928, y: 1168 }, { x: 1936, y: 1178 }, { x: 1940, y: 1185 }],
    },
    {
      id: "C-t2", outcome: "relocate", label: "EV-2310 · MOVED +99.8 m",
      meta: "occupant met · 4 photos · 14 Feb",
      points: [{ x: 1952, y: 1198 }, { x: 1966, y: 1214 }, { x: 1980, y: 1228 }, { x: 1992, y: 1242 }, { x: 2004, y: 1254 }, { x: 2008, y: 1258 }],
    },
  ],
  pipeline: [
    { stage: "parse", ms: 13, note: "6 tokens · 'Mndr'→'mandir' · survey-no grammar matched S.No 88/1" },
    { stage: "anchor", ms: 9, note: "hwy × gaothan edge → E 001 955 / N 001 213 · σ 300 m" },
    { stage: "retrieve", ms: 34, note: "parcels 2 epochs conflict · gazette 1 · PIN 1 → 3 after dedupe" },
    { stage: "memory", ms: 6, note: "prior PL-RJG-0231 · STALE 210 d · refute count 2 → memory weight damped 0.55→0.22" },
    { stage: "evidence-prior", ms: 14, note: "NOT_FOUND at stored point + relocate fix +99.8 m SE with occupant attestation" },
    { stage: "score", ms: 10, note: "r1 0.79 · r2 0.72 (Δ 0.07) · spatial split 99.8 m" },
    { stage: "policy", ms: 4, note: "margin & spatial gates both fail → CONTESTED · hold for field sign-off" },
  ],
  gateNote: "Two physically separated claims for the same address. Never auto-resolve; field officer decides.",
};

const D: Scenario = {
  id: "scn-d",
  raw: "\"Raju kirana stores\" wala ghar, Morya Colony, pani tanki jawal, Khed 410501",
  context: "name-only intake · no house number · sweep found nothing",
  parsed: [
    { t: "\"Raju kirana stores\"", k: "business" },
    { t: "wala ghar", k: "noise" },
    { t: "Morya Colony", k: "locality" },
    { t: "pani tanki jawal", k: "landmark" },
    { t: "Khed", k: "locality" },
    { t: "410501", k: "pin" },
  ],
  anchor: { x: 2080, y: 700 },
  anchorSigmaM: 350,
  memory: null,
  candidates: [
    {
      id: "C-D1", at: { x: 2060, y: 730 }, sigmaM: 220,
      canonical: "Morya Colony locality centroid",
      source: "Gazette Registry", sourceRef: "GAZ-2016-MORYA", score: 0.44,
      parts: { text: 0.58, component: 0.2, source: 0.85, evidence: 0, memory: 0, freshness: 0.7 },
      distFromAnchorM: 36.1, evidenceSupport: 0,
      conflict: "no house-number token · locality-level only",
    },
    {
      id: "C-D2", at: { x: 2240, y: 880 }, sigmaM: 140,
      canonical: "Khed gaothan house-line 4 (near tank)",
      source: "Municipal Parcel DB", sourceRef: "PRCL-KHD-L4", score: 0.37,
      parts: { text: 0.44, component: 0.18, source: 0.9, evidence: 0, memory: 0, freshness: 0.8 },
      distFromAnchorM: 241.6, evidenceSupport: 0,
    },
    {
      id: "C-D3", at: { x: 2290, y: 1205 }, sigmaM: 90,
      canonical: "SH-27 frontage parcel 229",
      source: "Municipal Parcel DB", sourceRef: "PRCL-KHD-229", score: 0.29,
      parts: { text: 0.3, component: 0.12, source: 0.9, evidence: 0, memory: 0, freshness: 0.8 },
      distFromAnchorM: 546.0, evidenceSupport: 0,
    },
  ],
  trails: [
    {
      id: "D-t1", outcome: "search", label: "EV-2301 · SWEEP 41 min",
      meta: "no signboard · residents unsure · 12 Feb",
      points: [
        { x: 2020, y: 660 }, { x: 2020, y: 740 }, { x: 2050, y: 740 }, { x: 2050, y: 660 },
        { x: 2080, y: 660 }, { x: 2080, y: 740 }, { x: 2110, y: 740 }, { x: 2110, y: 660 },
        { x: 2140, y: 660 }, { x: 2140, y: 740 },
      ],
    },
  ],
  pipeline: [
    { stage: "parse", ms: 11, note: "no house-no · business name only · 'pani tanki' → water tank landmark" },
    { stage: "anchor", ms: 7, note: "colony centroid E 002 080 / N 000 700 · σ 350 m" },
    { stage: "retrieve", ms: 29, note: "3 candidates · none better than locality level" },
    { stage: "memory", ms: 4, note: "no prior · cold start" },
    { stage: "evidence-prior", ms: 8, note: "1 sweep visit · 41 min spiral · zero matches · integrity clear" },
    { stage: "score", ms: 8, note: "r1 0.44 · r2 0.37 · r3 0.29 — all below 0.60 floor" },
    { stage: "policy", ms: 3, note: "UNPLACEABLE → open field task with local-inquiry script" },
  ],
  gateNote: "Nothing meets the 0.60 floor. Creating a field task is the honest answer.",
};

export const SCENARIOS: Scenario[] = [A, B, C, D];

/* ================= places (memory graph) ================= */

export const PLACES: Place[] = [
  { id: "PL-AMB-0142", label: "Urmi Septic Tank Services", address: "14/2-B, Station Rd (rear), Ambegaon BK 412406",
    at: { x: 700, y: 580 }, sigmaM: 4.2, confidence: 0.93, state: "STABLE", visits: 3,
    lastVerified: "14 Feb 2026", lastVerifiedDays: 1, sources: ["Field Memory", "Municipal Parcel DB"],
    driftM: 1.8, contradictions: [], note: "Signboard confirmed facing lane; entrance on west side behind Old Bus Stand." },
  { id: "PL-CHK-0087", label: "Shanti Niwas (Flt 1–12)", address: "TPS-Chakan 3/114, Tilak Rd, opp Ram Mandir",
    at: { x: 1172, y: 826 }, sigmaM: 6.1, confidence: 0.88, state: "STABLE", visits: 2,
    lastVerified: "12 Jan 2026", lastVerifiedDays: 34, sources: ["Municipal Parcel DB", "Field Memory"],
    driftM: 2.4, contradictions: [], note: "Entrance spine N-side; flats numbered clockwise from stairwell." },
  { id: "PL-RJG-0231", label: "S.No 88/1 — Pawar residence", address: "Gaothan, Pune–Nashik Hwy, Rajgurunagar 410505",
    at: { x: 1940, y: 1185 }, sigmaM: 5.0, confidence: 0.41, state: "CONTESTED", visits: 4,
    lastVerified: "18 Jul 2025", lastVerifiedDays: 212, sources: ["Gazette Registry", "Municipal Parcel DB"],
    driftM: 99.8,
    contradictions: [
      "Gazette 2004 point vs Nov-2025 resurvey differ by 99.8 m",
      "2 refute visits at stored point; 1 relocate fix SE of Hanuman Mandir",
      "Stored point contradicts occupant attestation (EV-2310)",
    ],
    note: "Resurvey places house line SE of Hanuman Mandir. Held for field sign-off before memory rewrite." },
  { id: "PL-KHD-0310", label: "Raju Kirana Stores (reported)", address: "Morya Colony, Khed 410501 — name only",
    at: { x: 2060, y: 730 }, sigmaM: 220, confidence: 0.22, state: "PROVISIONAL", visits: 1,
    lastVerified: "never", lastVerifiedDays: -1, sources: ["Caller report"],
    driftM: 0, contradictions: ["41 min structured sweep found no signboard (EV-2301)"],
    note: "Placeholder at locality centroid. Not routable. Awaiting local inquiry." },
  { id: "PL-AMB-0201", label: "Old Bus Stand", address: "Station Rd, Ambegaon BK",
    at: { x: 730, y: 560 }, sigmaM: 8.0, confidence: 0.95, state: "STABLE", visits: 5,
    lastVerified: "15 Feb 2026", lastVerifiedDays: 0, sources: ["Field Memory", "Gazette Registry"],
    driftM: 0.9, contradictions: [], note: "Monument-class calibration landmark. Re-fixed quarterly." },
  { id: "PL-CHK-0102", label: "Ram Mandir, Tilak Rd", address: "Tilak Rd, Chakan",
    at: { x: 1240, y: 858 }, sigmaM: 5.0, confidence: 0.96, state: "STABLE", visits: 6,
    lastVerified: "13 Feb 2026", lastVerifiedDays: 2, sources: ["Field Memory"],
    driftM: 1.1, contradictions: [], note: "Used as anchor for landmark-relative intake on Tilak Rd." },
  { id: "PL-AMB-0155", label: "ZP Primary School", address: "ZP School Rd, Ambegaon BK",
    at: { x: 900, y: 700 }, sigmaM: 9.0, confidence: 0.55, state: "STALE", visits: 2,
    lastVerified: "09 Jan 2025", lastVerifiedDays: 403, sources: ["Gazette Registry"],
    driftM: 18.0, contradictions: ["Local report: gate line shifted ~18 m north after wall rebuild (EV-2305)"],
    note: "No visits in 403 days. Entrance midpoint likely wrong; routing edge flagged." },
  { id: "PL-RJG-0245", label: "Hanuman Mandir (gaothan)", address: "Pune–Nashik Hwy, Rajgurunagar",
    at: { x: 1995, y: 1242 }, sigmaM: 4.5, confidence: 0.94, state: "STABLE", visits: 4,
    lastVerified: "14 Feb 2026", lastVerifiedDays: 1, sources: ["Field Memory"],
    driftM: 1.2, contradictions: [], note: "Anchor landmark for gaothan-side intake east of the highway." },
  { id: "PL-KHD-0298", label: "Gawade Flour Mill", address: "House-line 4, Khed gaothan",
    at: { x: 2240, y: 880 }, sigmaM: 14, confidence: 0.48, state: "PROVISIONAL", visits: 1,
    lastVerified: "14 Feb 2026", lastVerifiedDays: 1, sources: ["Municipal Parcel DB"],
    driftM: 6.2, contradictions: ["Unit number unreadable at visit (rain glare) — signage only"],
    note: "Structure matches parcel; unit attribution unconfirmed." },
  { id: "PL-CHK-0090", label: "Tilak Rd 114 (gazette holdover)", address: "Tilak Rd, Chakan",
    at: { x: 1198, y: 846 }, sigmaM: 12, confidence: 0.31, state: "RETIRED", visits: 0,
    lastVerified: "never", lastVerifiedDays: -1, sources: ["Gazette Registry"],
    driftM: 0, contradictions: ["Superseded by TPS resurvey — merged into PL-CHK-0087", "Still referenced by 2 legacy records"],
    note: "Retired. Kept for audit lineage; suppressed from candidate index." },
];

/* ================= field evidence ================= */

export const VISITS: FieldVisit[] = [
  { id: "EV-2312", day: "15 Feb 2026", ts: "09:41", placeId: "PL-AMB-0201", placeLabel: "Old Bus Stand",
    officer: "S. Jadhav", device: "GS-07 · u-blox M10", outcome: "CONFIRMED",
    point: { x: 730, y: 560 }, offsetM: 0.9, fix: { cepM: 2.1, hdop: 0.8, sats: 17 }, photos: 2, dwellS: 96,
    motion: "STATIONARY", integrity: { mock: false, timeSkewS: 0.3, trailSigmaM: 1.2 }, quality: 0.95,
    note: "Quarterly calibration fix at known monument." },
  { id: "EV-2311", day: "14 Feb 2026", ts: "17:22", placeId: "PL-AMB-0142", placeLabel: "Urmi Septic Tank Services",
    officer: "R. Pawar", device: "GS-04 · u-blox M10", outcome: "CONFIRMED",
    point: { x: 701, y: 581 }, offsetM: 1.4, fix: { cepM: 2.8, hdop: 0.9, sats: 15 }, photos: 3, dwellS: 84,
    motion: "STATIONARY", integrity: { mock: false, timeSkewS: 0.5, trailSigmaM: 1.6 }, quality: 0.93,
    note: "Signboard legible; entrance west side as recorded." },
  { id: "EV-2310", day: "14 Feb 2026", ts: "15:03", placeId: "PL-RJG-0231", placeLabel: "S.No 88/1 — Pawar residence",
    officer: "S. Jadhav", device: "GS-07 · u-blox M10", outcome: "MOVED",
    point: { x: 2008, y: 1258 }, offsetM: 99.8, fix: { cepM: 3.1, hdop: 1.0, sats: 14 }, photos: 4, dwellS: 142,
    motion: "WALKING", integrity: { mock: false, timeSkewS: 0.4, trailSigmaM: 2.8 }, quality: 0.88,
    note: "Occupant met at new kitchen line SE of Hanuman Mandir; 4 photos incl. house plate." },
  { id: "EV-2309", day: "14 Feb 2026", ts: "14:12", placeId: "PL-RJG-0231", placeLabel: "S.No 88/1 — Pawar residence",
    officer: "S. Jadhav", device: "GS-07 · u-blox M10", outcome: "NOT_FOUND",
    point: { x: 1940, y: 1185 }, offsetM: 0.0, fix: { cepM: 2.6, hdop: 0.9, sats: 16 }, photos: 2, dwellS: 210,
    motion: "STATIONARY", integrity: { mock: false, timeSkewS: 0.4, trailSigmaM: 1.4 }, quality: 0.86,
    note: "Stored point is an open yard. Neighbours: family rebuilt toward temple ~2 yrs ago." },
  { id: "EV-2308", day: "14 Feb 2026", ts: "11:47", placeId: "PL-KHD-0298", placeLabel: "Gawade Flour Mill",
    officer: "A. Shaikh", device: "GS-11 · u-blox M8", outcome: "PARTIAL",
    point: { x: 2240, y: 881 }, offsetM: 6.2, fix: { cepM: 4.4, hdop: 1.4, sats: 11 }, photos: 1, dwellS: 63,
    motion: "WALKING", integrity: { mock: false, timeSkewS: 1.1, trailSigmaM: 3.9 }, quality: 0.64,
    note: "Signage matches parcel; unit number unreadable in rain glare." },
  { id: "EV-2307", day: "13 Feb 2026", ts: "18:55", placeId: "PL-CHK-0102", placeLabel: "Ram Mandir, Tilak Rd",
    officer: "R. Pawar", device: "GS-04 · u-blox M10", outcome: "CONFIRMED",
    point: { x: 1240, y: 858 }, offsetM: 1.1, fix: { cepM: 2.2, hdop: 0.8, sats: 16 }, photos: 1, dwellS: 58,
    motion: "STATIONARY", integrity: { mock: false, timeSkewS: 0.6, trailSigmaM: 1.1 }, quality: 0.92,
    note: "Anchor check for Tilak Rd landmark-relative intake." },
  { id: "EV-2306", day: "13 Feb 2026", ts: "16:31", placeId: "PL-CHK-0087", placeLabel: "Shanti Niwas",
    officer: "A. Shaikh", device: "GS-11 · u-blox M8", outcome: "CONFIRMED",
    point: { x: 1171, y: 828 }, offsetM: 2.4, fix: { cepM: 2.9, hdop: 1.0, sats: 13 }, photos: 2, dwellS: 77,
    motion: "STATIONARY", integrity: { mock: false, timeSkewS: 0.8, trailSigmaM: 2.0 }, quality: 0.90,
    note: "Flt 7 letterbox visible from Tilak Rd; stairwell clockwise." },
  { id: "EV-2305", day: "13 Feb 2026", ts: "13:20", placeId: "PL-AMB-0155", placeLabel: "ZP Primary School",
    officer: "S. Jadhav", device: "GS-07 · u-blox M10", outcome: "MOVED",
    point: { x: 900, y: 718 }, offsetM: 18.0, fix: { cepM: 3.3, hdop: 1.1, sats: 12 }, photos: 3, dwellS: 118,
    motion: "WALKING", integrity: { mock: false, timeSkewS: 0.7, trailSigmaM: 2.6 }, quality: 0.81,
    note: "Gate line shifted ~18 m north after boundary wall rebuild." },
  { id: "EV-2304", day: "13 Feb 2026", ts: "10:05", placeId: "PL-KHD-0310", placeLabel: "Raju Kirana Stores (reported)",
    officer: "A. Shaikh", device: "GS-11 · u-blox M8", outcome: "NOT_FOUND",
    point: { x: 2080, y: 700 }, offsetM: 24.4, fix: { cepM: 4.8, hdop: 1.5, sats: 10 }, photos: 0, dwellS: 2460,
    motion: "WALKING", integrity: { mock: false, timeSkewS: 1.3, trailSigmaM: 4.4 }, quality: 0.55,
    note: "41 min structured sweep; no signboard; residents unsure of the name." },
  { id: "EV-2303", day: "12 Feb 2026", ts: "19:40", placeId: "PL-CHK-0102", placeLabel: "Ram Mandir, Tilak Rd",
    officer: "M. Kale", device: "GS-19 · phone A-GPS", outcome: "CONFIRMED",
    point: { x: 1240, y: 858 }, offsetM: 1.1, fix: { cepM: 9.8, hdop: 3.2, sats: 6 }, photos: 1, dwellS: 12,
    motion: "STATIONARY", integrity: { mock: true, timeSkewS: 48.2, trailSigmaM: 11.7 }, quality: 0.18,
    note: "REJECTED — mock-provider flag + 48 s clock skew + 12 s dwell. Held out of priors; device GS-19 pulled for review." },
  { id: "EV-2302", day: "12 Feb 2026", ts: "17:12", placeId: "PL-AMB-0142", placeLabel: "Urmi Septic Tank Services",
    officer: "R. Pawar", device: "GS-04 · u-blox M10", outcome: "CONFIRMED",
    point: { x: 702, y: 581 }, offsetM: 2.2, fix: { cepM: 3.2, hdop: 1.0, sats: 14 }, photos: 2, dwellS: 71,
    motion: "STATIONARY", integrity: { mock: false, timeSkewS: 0.9, trailSigmaM: 1.9 }, quality: 0.91,
    note: "Routine recheck on memory refresh cycle." },
  { id: "EV-2301", day: "12 Feb 2026", ts: "09:58", placeId: "PL-KHD-0310", placeLabel: "Raju Kirana Stores (reported)",
    officer: "S. Jadhav", device: "GS-07 · u-blox M10", outcome: "NOT_FOUND",
    point: { x: 2140, y: 740 }, offsetM: 80.7, fix: { cepM: 4.1, hdop: 1.3, sats: 12 }, photos: 0, dwellS: 1500,
    motion: "WALKING", integrity: { mock: false, timeSkewS: 1.0, trailSigmaM: 3.6 }, quality: 0.52,
    note: "Second sweep along tank line; nothing matching 'Raju' signboard." },
];

/* ================= verification queue ================= */

export const CASES: VerifyCase[] = [
  { id: "VQ-4812", kind: "VERIFY_FIRST", placeLabel: "S.No 88/1 — Pawar residence", placeId: "PL-RJG-0231",
    rawAddress: "S No 88/1, gaothan side, near Hanuman Mndr, Pune Nashik Hwy, Rajgurunagar 410505",
    priority: "P1", ageDays: 0, slaHoursLeft: 6, slaHoursTotal: 48,
    reasonCodes: ["MEM_DRIFT_99.8M", "STALE_212D", "OCCUPANT_ATTESTED"],
    score: 0.79, margin: 0.07, at: { x: 2008, y: 1258 }, sigmaM: 5.4,
    recommendation: "Dispatch to resurvey point SE of Hanuman Mandir; photograph house line; obtain occupant signature, then rewrite memory point." },
  { id: "VQ-4811", kind: "VERIFY_FIRST", placeLabel: "Urmi Septic Tank Services", placeId: "PL-AMB-0142",
    rawAddress: "URMI SEPTIC TANK SERVICRS!! 14/2-B, behind old bus stand?? Ambegaon bk, 412406",
    priority: "P2", ageDays: 0, slaHoursLeft: 22, slaHoursTotal: 72,
    reasonCodes: ["MARGIN_0.06_LT_GATE", "R1R2_COLOCATED_5.1M"],
    score: 0.88, margin: 0.06, at: { x: 700, y: 580 }, sigmaM: 4.2,
    recommendation: "Low risk: r1/r2 co-located within 5.1 m. Single photo fix at entrance suffices to close." },
  { id: "VQ-4809", kind: "CONTESTED", placeLabel: "Gawade Flour Mill", placeId: "PL-KHD-0298",
    rawAddress: "Gawade flour mill, h line 4, Khed gaothan",
    priority: "P2", ageDays: 1, slaHoursLeft: 30, slaHoursTotal: 72,
    reasonCodes: ["SIGN_PARTIAL", "UNIT_NO_MISSING"],
    score: 0.48, at: { x: 2240, y: 880 }, sigmaM: 14,
    recommendation: "Capture unit number plate in dry conditions; if absent twice, demote to locality-level place." },
  { id: "VQ-4807", kind: "MOVED_SUSPECTED", placeLabel: "ZP Primary School", placeId: "PL-AMB-0155",
    rawAddress: "ZP school, Ambegaon BK",
    priority: "P2", ageDays: 2, slaHoursLeft: 41, slaHoursTotal: 96,
    reasonCodes: ["GATE_SHIFT_18.0M", "LAST_VERIFIED_403D"],
    at: { x: 900, y: 718 }, sigmaM: 9,
    recommendation: "Re-fix entrance midpoint after wall rebuild; update routing edge and refresh memory point." },
  { id: "VQ-4805", kind: "UNPLACEABLE", placeLabel: "Raju Kirana Stores (reported)", placeId: "PL-KHD-0310",
    rawAddress: "\"Raju kirana stores\" wala ghar, Morya Colony, pani tanki jawal, Khed 410501",
    priority: "P1", ageDays: 1, slaHoursLeft: 11, slaHoursTotal: 48,
    reasonCodes: ["NO_HOUSE_NO", "SWEEP_NO_MATCH", "NAME_ONLY"],
    score: 0.44, at: { x: 2060, y: 730 }, sigmaM: 220,
    recommendation: "Local inquiry at gram panchayat; ask for alternate trade name; query water-tank line households." },
  { id: "VQ-4803", kind: "REVERIFICATION", placeLabel: "Old Bus Stand", placeId: "PL-AMB-0201",
    rawAddress: "old bus stand, Ambegaon BK",
    priority: "P3", ageDays: 3, slaHoursLeft: 96, slaHoursTotal: 168,
    reasonCodes: ["CALIBRATION_DUE"],
    at: { x: 730, y: 560 }, sigmaM: 8,
    recommendation: "Quarterly monument recheck; two-minute stationary fix, no occupant needed." },
  { id: "VQ-4801", kind: "REVERIFICATION", placeLabel: "Ram Mandir, Tilak Rd", placeId: "PL-CHK-0102",
    rawAddress: "ram mandir, tilak rd, chakan",
    priority: "P3", ageDays: 4, slaHoursLeft: 120, slaHoursTotal: 168,
    reasonCodes: ["EPOCH_DRIFT_CHECK"],
    at: { x: 1240, y: 858 }, sigmaM: 5,
    recommendation: "Routine anchor recheck after SEAL-01 epoch 2025-W46 retrace." },
  { id: "VQ-4799", kind: "CONTESTED", placeLabel: "Tilak Rd 114 (gazette holdover)", placeId: "PL-CHK-0090",
    rawAddress: "tilak rd 114, chakan",
    priority: "P3", ageDays: 6, slaHoursLeft: 140, slaHoursTotal: 168,
    reasonCodes: ["DUPLICATE_OF_PL-CHK-0087", "LEGACY_REFS_2"],
    recommendation: "Confirm retirement; remap the 2 legacy references to PL-CHK-0087 and suppress from index." },
  { id: "VQ-4796", kind: "UNPLACEABLE", placeLabel: "opp new bandhara (caller report)",
    rawAddress: "ghar opp new bandhara, khed side",
    priority: "P2", ageDays: 1, slaHoursLeft: 52, slaHoursTotal: 72,
    reasonCodes: ["LANDMARK_NOT_INDEXED", "VAGUE_RELATION"],
    recommendation: "Call back for cross-street or nearest named structure; do not dispatch blind." },
  { id: "VQ-4790", kind: "MOVED_SUSPECTED", placeLabel: "Shakti Flour Mill, Station Rd",
    rawAddress: "shakti flour mill, station rd, ambegaon",
    priority: "P2", ageDays: 5, slaHoursLeft: 18, slaHoursTotal: 96,
    reasonCodes: ["TRAIL_OFFSET_64M", "POWER_FEED_GAP_22/4"],
    at: { x: 704, y: 444 }, sigmaM: 11,
    recommendation: "Walk 64 m NE along Station Rd; locate transformer pole 22/4 and re-fix entrance." },
];

/* ================= system overview ================= */

const SERIES: DayStat[] = [
  { day: "01 Feb", resolutions: 364, warmAcc: 0.9, coldAcc: 0.61 },
  { day: "02 Feb", resolutions: 402, warmAcc: 0.91, coldAcc: 0.63 },
  { day: "03 Feb", resolutions: 388, warmAcc: 0.89, coldAcc: 0.6 },
  { day: "04 Feb", resolutions: 441, warmAcc: 0.92, coldAcc: 0.64 },
  { day: "05 Feb", resolutions: 419, warmAcc: 0.9, coldAcc: 0.62 },
  { day: "06 Feb", resolutions: 356, warmAcc: 0.88, coldAcc: 0.58 },
  { day: "07 Feb", resolutions: 301, warmAcc: 0.9, coldAcc: 0.6 },
  { day: "08 Feb", resolutions: 372, warmAcc: 0.91, coldAcc: 0.62 },
  { day: "09 Feb", resolutions: 428, warmAcc: 0.93, coldAcc: 0.65 },
  { day: "10 Feb", resolutions: 455, warmAcc: 0.92, coldAcc: 0.66 },
  { day: "11 Feb", resolutions: 430, warmAcc: 0.91, coldAcc: 0.63 },
  { day: "12 Feb", resolutions: 447, warmAcc: 0.92, coldAcc: 0.64 },
  { day: "13 Feb", resolutions: 463, warmAcc: 0.93, coldAcc: 0.67 },
  { day: "14 Feb", resolutions: 431, warmAcc: 0.94, coldAcc: 0.65 },
];

const SERVICES: ServiceHealth[] = [
  { name: "parse-svc", role: "address parsing & tokenisation", p50ms: 12, errPct: 0.2, queueDepth: 0, status: "OK" },
  { name: "cand-idx", role: "gazetteer candidate retrieval", p50ms: 31, errPct: 0.1, queueDepth: 3, status: "OK" },
  { name: "evidence-store", role: "visit files & GPS blobs", p50ms: 44, errPct: 0.0, queueDepth: 0, status: "OK" },
  { name: "memory-graph", role: "place memory & priors", p50ms: 18, errPct: 0.3, queueDepth: 1, status: "OK" },
  { name: "verify-orch", role: "field task orchestration", p50ms: 480, errPct: 1.8, queueDepth: 137, status: "DEGRADED" },
  { name: "audit-ledger", role: "hash-chained event log", p50ms: 9, errPct: 0.0, queueDepth: 0, status: "OK" },
];

export const OVERVIEW: SystemOverview = {
  kpis: {
    resolutionsToday: 431,
    resolutionsDeltaPct: 6.4,
    autoDecidedPct: 0.626,
    medianResolveMs: 214,
    openCases: 10,
    p1Cases: 3,
  },
  warmCold: { warm: 0.914, cold: 0.628, warmN: 2310, coldN: 1464 },
  series: SERIES,
  services: SERVICES,
};
